base/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('base.views',
    url(r'^$', 'index', name='index'),
    url(r'^howto/$', 'howto', name='howto'),
    url(r'^success/$', 'success', name='success'),
    url(r'^test/$', 'test', name='test'),
    url(r'^get_flatpage_url/$', 'get_flatpage_url', name='get_flatpage_url'),
    url(r'^get_form_url/$', 'get_form_url', name='get_form_url'),
    url(r'^plan/$', 'plan', name='plan'),
    url(r'^probki_value/$', 'get_yandex_probki', name='get_yandex_probki'),
    url(r'^flatpages/(?P<slug>.*)/$', 'flat_page', name='flat_page'),
    url(r'^search/$', 'search', name='search'),

    
    url(r'^check_fp_menuitem_exists/$', 
        'check_fp_menuitem_exists',
        name='check_fp_menuitem_exists'),
)

calendar_expo/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('calendar_expo.views',
    url(r'^$', 'events', name='events'),
    url(r'^api/event_titles/$', 'event_title_list', name='event_title_list'),
    url(r'^api/events/$', 'api_event_list', name='api_event_list'),
    url(r'^(?P<slug>.*)/ics/$', 'event_ics', name='event_ics'),
    url(r'^(?P<slug>.*)/csv/$', 'event_csv', name='event_csv'),
    url(r'^(?P<slug>.*)/$', 'detail', name='detail'),
)

howtopage/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('howtopage.views',
    url(r'^$', 'howtopage', name='howtopage'),
)

kvc/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import forms_builder.forms.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', name='sitemap_xml'),
    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns('',
    url(r'^$', 'base.views.index', name='index'),
    url(r'^current/', include('base.urls', namespace='base')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^calendar/', include('calendar_expo.urls', namespace='calendar')),
    url(r'^dynamic_forms/', include('dynamic_forms.urls', namespace='dynamic_forms')),
    url(r'^filestorage/', include('filestorage.urls', namespace='filestorage')),
    url(r'^howtopage/', include('howtopage.urls', namespace='howtopage')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^organizers/', include('organizers_app.urls', namespace='organizers')),
    url(r'^press/', include('press_app.urls', namespace='press')),
    url(r'^partners/', include('partners.urls', namespace='partners')),
    url(r'^plans/', include('plans.urls', namespace='plans')),
    url(r'^publications/', include('publications.urls', namespace='publications')),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forms/', include(forms_builder.forms.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    url(r'^$', 'base.views.index', name='i18n_index'),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

urlpatterns += patterns('',
    url(r'^(?P<url>.*)/$', 'base.views.flatpage', name='base.views.flatpage'),
)

urlpatterns += i18n_patterns('',
    url(r'^(?P<url>.*)/$', 'base.views.flatpage', name='i18n_flatpage'),
)

plans/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('plans.views',
    url(r'^show/$', 'show', name='show'),
    url(r'^zoomify_test/$', 'zoomify_test'),
    url(r'^api/planicons/$', 'api_planicons', name='api_planicons'),
    url(r'^api/planimages/$', 'api_planimages', name='api_planimages'),
    url(r'^api/plans/$', 'api_plans', name='api_plans'),
    url(r'^api/plans/(?P<pk>\d+)/$', 'api_plan_detail', name='api_plan_detail'),
    url(r'^api/plans/actual/$', 'actual_plan_api', name='actual_plan_api'),
)

base/forms.py
#coding: utf-8
from django.utils.translation import ugettext_lazy as _

from .fields import LocaleModelSelect2MultipleField, LocaleModelChoiceField


class LocaleFieldModelFormMixin(object):
    def get_locale_field(self, model, request, multiple=True):
        kwargs = dict(  queryset=model.objects.all(),
                        required=False,
                        request=request)
        if multiple:
            return LocaleModelSelect2MultipleField(**kwargs)
        else:
            return LocaleModelChoiceField(**kwargs)

    def get_empty_label(self, request=None):
        return _(u'Любое')

base/views.py
#coding: utf-8
import datetime
import itertools
import json
import requests

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, Http404
from django.shortcuts import redirect
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic import ListView

from calendar_expo.models import Event, BannerItem, MainBigBanner
from dynamic_forms.models import Form
from news.forms import SubscribeEmailForm
from news.models import NewsPage
from partners.models import Partner as PartnerBannerItem

from .models import FlatPage, SliderItem, AbstractPage, EmailTemplate
from .models import SystemTunes, MenuItem
from .utils import send_email


class CTXMixin(object):
    def get_context_data(self, **kwargs):
        ctx = super(CTXMixin, self).get_context_data(**kwargs)
        try:
            ctx['page_title'] = self.model._meta.verbose_name_plural
        except: pass
        ctx['subscribe_form'] = SubscribeEmailForm(self.request)
        return ctx


class IndexPage(CTXMixin, TemplateView):
    u''' Главная страница '''
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        # TODO: need refact
        news = NewsPage.objects.active_pages(self.request)
        if news.count() > 3:
            news =news[:3]
        events = Event.objects.active_pages(self.request
                            ).filter(end_date__gte=datetime.date.today())
        if events.count() > 3:
            events = events[:3]
        sliders = SliderItem.objects.active_pages(self.request
                                    ).filter(is_active=True)
        banners = BannerItem.objects.active(self.request
                                    ).filter(is_active=True,
                                    event__end_date__gte=datetime.date.today())
        partner_banners = PartnerBannerItem.objects.filter(on_main_page=True,
            flr_image__isnull=False)
        if partner_banners.count() > 15:
            partner_banners = partner_banners[:15]
        big_banners = MainBigBanner.objects.active(self.request
                                            ).filter(is_active=True,)
        if big_banners.count() > 2:
            big_banners = big_banners[:2]
        ctx.update({
                    'banners': banners,
                    'big_banners': big_banners,
                    'calendar_events': events,
                    'news': news,
                    'partner_banners': partner_banners,
                    'sliders': sliders,
        })
        return ctx
index = IndexPage.as_view()
success = IndexPage.as_view(template_name='success.html')
test = IndexPage.as_view(template_name='test.html')
plan = IndexPage.as_view(template_name='plan.html')
howto = IndexPage.as_view(template_name='howto.html')

class ListPage(CTXMixin, ListView):
    model = NewsPage
    paginate_by = 10
    template_name = 'basecontent.html'  
news_list = ListPage.as_view()


class DetailPage(CTXMixin, DetailView):
    template_name = 'object_detail.html'
    context_object_name = 'detail_page'

    def get_template_names(self):
        if self.get_object() and self.get_object().template:
            return [self.get_object().template]
        else:
            return super(DetailPage, self).get_template_names()

    def get(self, request, *args, **kwargs):
        if self.get_object() in self.get_queryset().active_pages(request):
            return super(DetailPage, self).get(request, *args, **kwargs)
        else:
            return redirect(reverse('base:index'))
flat_page = DetailPage.as_view(model=FlatPage)


class FlatPageDetail(DetailPage):
    model=FlatPage
    url_kwarg = 'url'

    def get_object(self, queryset=None):    
        if queryset is None:
            queryset = self.get_queryset()
        url = self.kwargs.get(self.url_kwarg, None)
        if not url.startswith('/'): url = '/' + url
        if not url.endswith('/') and settings.APPEND_SLASH: url += '/'
        if url is not None:
            obj = queryset.filter(url_path=url).last()
            if not obj: raise Http404
            return obj
flatpage = FlatPageDetail.as_view()


def check_fp_menuitem_exists(request):
    if request.GET.get('pk'):
        mi = MenuItem.objects.filter(fp=request.GET.get('pk')).last()
        if mi:
            res = dict( exist=True,
                        mi=dict(pk=mi.pk, url=mi.admin_link)
                    )
            return HttpResponse(json.dumps(res),
                                content_type="application/json")
    return HttpResponse(json.dumps(dict(exist=False)), 
                        content_type="application/json")


def get_flatpage_url(request):
    if request.GET.get('pk'):
        fp = FlatPage.objects.filter(pk=request.GET.get('pk')).last()
        if fp:
            return HttpResponse(json.dumps(fp.get_absolute_url()),
                                content_type="application/json")
    return HttpResponse(json.dumps(dict()), 
                        content_type="application/json")

def get_form_url(request):
    if request.GET.get('pk'):
        fp = Form.objects.published(for_user=request.user
                        ).filter(pk=request.GET.get('pk')
                        ).last()
        if fp:
            return HttpResponse(json.dumps(fp.get_absolute_url()),
                                content_type="application/json")
    return HttpResponse(json.dumps(dict()), 
                        content_type="application/json")

def get_flat_list(gen):
    return list(itertools.chain(*gen))

def get_subclass_queryset(model, filters):
    for sub_model in model.__subclasses__():
        if not sub_model.__subclasses__():
            yield sub_model.objects.filter(filters)
        #if sub_model.__subclasses__():
            #yield get_flat_list(get_subclass_queryset(sub_model, filters))
        #else:
            #yield sub_model.objects.filter(filters)

class Search(TemplateView):
    u''' поиск по сайту '''
    template_name = 'search.html'

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        ctx['search_results'] = self.get_pages()
        return ctx

    def get_pages(self):
        if self.request.GET.get('keyword'):
            filters = self.get_filters()
            res = get_subclass_queryset(AbstractPage, filters)
            return get_flat_list(res)

    def get_filters(self):
        dct = self.request.GET.get('keyword', '').split(' ')
        q = None
        for s in dct:
            prefix = {
                        'ru': 'ru',
                        'en': 'en',
                        'zh-cn': 'cn',
                }.get(self.request.LANGUAGE_CODE)
            fields = ['{0}_{1}'.format(prefix, f) for f in ('title', 'content', 'status')]
            expr1 = Q(**{
                            '{0}__{1}'.format(fields[0], 'isnull'): False,
                            fields[2]: 2,
            })
            expr2 = Q(**{'{0}__{1}'.format(fields[0], 'icontains'): s})
            expr3 = Q(**{'{0}__{1}'.format(fields[1], 'icontains'): s})
            expr = (expr1 & (expr2 | expr3))
            if q:
                q|= expr
            else:
                q = expr
        return q
search = Search.as_view()


def get_yandex_probki(request):
    url = 'http://jgo.maps.yandex.net/trf/stat.js?='
    r = requests.get(url)
    if r.status_code == 200:
        res = r.text[r.text.find('[')+1:-4].split('},{')[0][1:]
        res = res[res.find('level:"'):].split('"')[1]
        return HttpResponse(res)
    return HttpResponse(json.dumps(dict()))


class SendEmailMixin(object):
    def send_email(self, obj, email_tpl_type, to_attr):
        email_tpl = EmailTemplate.objects.filter(tpl_type=email_tpl_type).last()
        st = SystemTunes.objects.get_current()
        if email_tpl:
            bctx = dict(obj=obj,)
            send_email( 
                        subject=email_tpl.subject,
                        to = getattr(st,to_attr),
                        body_tpl = email_tpl.text,
                        body_context = bctx,
                        from_email = st.from_email
                    )

plans/views.py
#coding: utf-8
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache

from rest_framework import generics

from .models import PlanIcon, PlanImage, Plan
from .serializers import PlanIconSerializer, PlanImageSerializer, PlanSerializer

class PlanShow(TemplateView):
    template_name = 'plan_show.html'
show = PlanShow.as_view()

class PlanZoomifyTest(TemplateView):
    template_name = 'plan_zoomify_test.html'
zoomify_test = PlanZoomifyTest.as_view()


class PlanIconAPIList(generics.ListAPIView):
    model = PlanIcon
    serializer_class = PlanIconSerializer
api_planicons = PlanIconAPIList.as_view()


class PlanImageAPIList(generics.ListAPIView):
    model = PlanImage
    serializer_class = PlanImageSerializer

    @method_decorator(never_cache)
    def get(self, request, *args, **kwargs):
        return super(PlanImageAPIList, self).get(request, args, kwargs)
api_planimages = PlanImageAPIList.as_view()


class PlanAPIList(generics.ListAPIView):
    model = Plan
    serializer_class = PlanSerializer
api_plans = PlanAPIList.as_view()


class PlanAPIDetail(generics.RetrieveUpdateAPIView):
    model = Plan
    serializer_class = PlanSerializer
api_plan_detail = PlanAPIDetail.as_view()


class ActualPlanAPI(PlanAPIDetail):
    queryset=Plan.objects.filter(is_active=True)
    def get_object(self, queryset=None):
        return self.queryset.last()
actual_plan_api = ActualPlanAPI.as_view()

base/templates/mobile/base.html
{% load staticfiles %}
{% load block_render_tags i18n %}
{% spaceless %}
<!DOCTYPE html>
<html>

<head>
    {% block seo %}
    {% if current_menuitem.has_seo %}
    <title>{% render_locale_title request current_menuitem %} mobile</title>
    <meta name="description" content="{% render_locale_field request current_menuitem 'description' %}" />
    <meta name="keywords" content="{% render_locale_field request current_menuitem 'keywords' %}" />
    {% elif detail_page.get_seo %}
    <title>{% render_locale_title request detail_page %} mobile</title>
    <meta name="description" content="{% render_locale_field request detail_page 'description' %}" />
    <meta name="keywords" content="{% render_locale_field request detail_page 'keywords' %}" />
    {% elif systemtune %}
    <title>{% render_locale_title request systemtune %} mobile</title>
    <meta name="description" content="{% render_locale_field request systemtune 'description' %}" />
    <meta name="keywords" content="{% render_locale_field request systemtune 'keywords' %}" />
    {% else %}
    <title>{% if page_title %}{{page_title}}{%else%}ExpoForum{%endif%} mobile</title>
    <meta name="description" content="expoforum" />
    <meta name="keywords" content="expoforum" />
    {% endif %}
    <meta name="created" content="{% now "d M Y h:i" %}" />
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <link href="{% static "mobile/css/jquery-ui-1.10.4.custom.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "mobile/css/style.css" %}" rel="stylesheet" type="text/css" />
    

    <script type="text/javascript" src="{% static "mobile/js/jquery-1.11.0.min.js" %}"></script>
    <script type="text/javascript" src="{% static "mobile/js/jquery-ui-1.10.4.custom.min.js" %}"></script>
    <script type="text/javascript" src="{% static "mobile/js/jquery.ui.datepicker-ru.js" %}"></script>
    <script type="text/javascript" src="{% static "mobile/js/main.js" %}"></script>
    <!--[if lt IE 9]>
        <script src="{% static "mobile/js/html5shiv.js" %}"></script>
    <![endif]-->
    {% block headextrascripts%}
    {% endblock %}
</head>

{% block body %}
<body>
    {% block header %}
    <header>
        <div class="container">
            <div class="headmenu">
                <ul>
                    <li><a href="{% url 'calendar:events' %}">Календарь</a></li>
                    <li><a href="{% url 'base:plan' %}">План</a></li>
                    <li><a href="{% url 'howtopage:howtopage' %}">Как добраться</a></li>
                </ul>
            </div>
        </div>
    </header>
    {% endblock %}

    <section>
        <div class="container">
            <div class="headlogo">
                <a href="/"><img src="{% static "mobile/images/design/logo.png" %}" alt="ExpoForum"></a>
            </div>
            {% if header_block_content.info %}
                <div class="headcontacts">{{header_block_content.info.phone}}</div>
                <div class="clear"><a class="heademail" href="mailto:{{header_block_content.info.email}}">{{header_block_content.info.email}}</a></div>
            {% else %}
            <div class="headcontacts">
                +7 (812) <b>240-40-40</b> 
            </div>
            <div class="clear">
                <a href="mailto:info@expoforum.ru" class="heademail">info@expoforum.ru</a>
            </div>
            {% endif %}
        </div>
    </section>

    {% block maincontain %}
    <section></section>
    {% endblock %}

    <section>
        <div class="footersearch">
            <form class="" action="{% url 'base:search' %}?flavour=full" method="get">
                <input type="search" name="keyword" value="" placeholder="{% trans 'Поиск по сайту' %}">
                <button type="submit" class="bluebtn">{% trans 'Найти' %}</button>
            </form>
        </div>
    </section>
    <footer>
        <div class="container">
            <div>
                <p><a href="?flavour=full">{% trans 'Полная версия сайта' %}</a></p>
            </div>
            <div class="copyright">
                <p>{% trans 'Экспофорум &copy; 2014' %}</p>
            </div>
        </div>
    </footer>
</body>
{% endblock %}
</html>
{% endspaceless %}

base/templates/mobile/howto.html
{% extends 'basecontent.html' %}

{% load staticfiles %}
{% load i18n block_render_tags%}

{% block maincontain %}
<section>
    <div class="container">
        <div class="textblock">
            <h2>Как добраться</h2>
        </div>
        <div class="accordion closed">
            <h3 class="accordiontitle">На машине</h3>
            <div class="accordiontext">
                <div class="textblock">
                    <img src="{% static "mobile/images/map1.jpg" %}" alt="Карта">
                    <p>Описание последовательностей маршрута при проезде на машине из некой точки или с разных направлений ключевых магистралей. С пояснениями про развязки.</p>
                    <p>Предложение проложить маршрут с помощью специализированных сервисов:</p>
                    <p><a href="#">Маршрут проезда на Google Maps</a></p>
                    <p><a href="#">Маршрут с помощью приложения на вашем устройстве</a></p>
                    <p><a href="#">Схемы движения транспорта по территории парковки</a></p>
                </div>
            </div>
        </div>
        <div class="accordion closed">
            <h3 class="accordiontitle">На общественном транспорте</h3>
            <div class="accordiontext">
                <div class="textblock">
                    <h4>Посадка на площади возле памятника Троцкому</h4>
                    <img src="{% static "mobile/images/photo2.jpg" %}" alt="photo2">
                    <p class="busicon">36, 88, 149, 8А</p>
                    <p class="furgonicon">К-80, К-133, К-209</p>
                    <br>
                    <h4>Посадка со стороны Макдональдса</h4>
                    <img src="{% static "mobile/images/photo1.jpg" %}" alt="photo1" class="leftimg">
                    <p class="busicon">Бесплатный шатл-бас до Экспофорума</p>
                    <ul class="bustime">
                        <li>Интервал движения:</li>
                        <li>пн-пт — каждые 30 мин.</li>
                        <li>сб, вс — каждый час</li>
                        <li>в дни проведения выставок каждые 15 мин.</li>
                    </ul>
                    <p class="busicon">36, 88, 149, 8А</p>
                    <p class="trallicon">11, 3</p>
                    <p class="furgonicon">К-80, К-133, К-209</p>
                </div>
            </div>
        </div>
        <div class="accordion">
            <h3 class="accordiontitle">План территории</h3>
            <div class="accordiontext">
                <div class="textblock">
                    <p class="probki"><span class="lvl5 probkirate">5</span>
                    Уровень пробок в Санкт-Петербурге<br>по данным сервиса <a href="#">Яндекс.Пробки</a></p>
                </div>
                <div class="mapblock">
                    <a href="#" class="resizelink orange">развернуть</a>
                    <div class="mappart" id="mappart"></div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block headextrascripts %}
{{block.super}}
    <style>
        #mappart {
            width: 590px;
            height: 450px;
        }
    </style>
    
    {% if LANGUAGE_CODE == 'ru' %}
    <script src="http://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    {% elif LANGUAGE_CODE == 'en' %}
    <script src="http://api-maps.yandex.ru/2.1/?lang=en_US" type="text/javascript"></script>
    {% elif LANGUAGE_CODE == 'zh-cn' %}
    <script src="http://api-maps.yandex.ru/2.1/?lang=en_US" type="text/javascript"></script>
    {% endif %}
    <script type="text/javascript">
        ymaps.ready(init);

        function init() {
            var mylocation = [59.9, 30.32];
            var geolocation = ymaps.geolocation,
                myMap = new ymaps.Map('mappart', {
                    center: mylocation,
                    zoom: 10,
                    controls: ['fullscreenControl', 'searchControl', 'zoomControl', 'routeEditor'],
                });
            
            var actualProvider = new ymaps.traffic.provider.Actual({}, { infoLayerShown: true });
            actualProvider.setMap(myMap);

            navigator.geolocation.getCurrentPosition(function(position) {
                    var latitude = position.coords.latitude;
                    var longitude = position.coords.longitude;

                mylocation = [latitude, longitude];

                ymaps.route([
                    mylocation,
                    [59.76351, 30.35746]
                ]).then(function (route) {
                        myMap.geoObjects.add(route);
                        var points = route.getWayPoints(),
                        lastPoint = points.getLength() - 1;
                        points.options.set('preset', 'islands#blueStretchyIcon');
                        points.get(0).properties.set('iconContent', 'Вы здесь');
                        points.get(lastPoint).properties.set('iconContent', 'ЭКСПОФОРУМ');
                    }, function (error) {
                    alert('Возникла ошибка: ' + error.message);
                });
            });
        }
    </script>
    <script type="text/javascript">
        function get_probki_data() {
            var url = '{% url 'base:get_yandex_probki' %}'
            $.ajax({
                url: url,
                success: function( data ) {
                    $('p.probki').remove();
                    $('div.textblock.maps').append('<p class=\"probki\"><span class=\"lvl5 probkirate\">'+data+'</span>Уровень пробок в Санкт-Петербурге<br>по данным сервиса Яндекс.Пробки</p>')
                }
            });
        };
        $(document).ready(get_probki_data());
    </script>
{% endblock %}

base/templates/mobile/plan.html
{% extends 'basecontent.html' %}

{% load staticfiles %}
{% load i18n block_render_tags%}

{% block maincontain %}
<section>
    <div class="textblock">
        <h2>План комплекса</h2>
    </div>
    <div class="planblock">
        <a href="#" class="resizelink lightblue">развернуть</a>
        <ul class="layers">
            <li class="layer active"><img src="{% static "mobile/images/plan1.png" %}" alt="flor4"></li>
            <li class="layer"><img src="{% static "mobile/images/plan1.png" %}" alt="flor3"></li>
            <li class="layer"><img src="{% static "mobile/images/plan1.png" %}" alt="flor2"></li>
            <li class="layer"><img src="{% static "mobile/images/plan1.png" %}" alt="flor1"></li>
        </ul>
        <ul class="layersbtns">
            <li><a href="#" class="button lightblue active">4 этаж</a></li>
            <li><a href="#" class="button lightblue">3 этаж</a></li>
            <li><a href="#" class="button lightblue">2 этаж</a></li>
            <li><a href="#" class="button lightblue">1 этаж</a></li>
        </ul>
    </div>
    <a href="#" class="planlink">Схема движения транспорта по территории</a>
</div>
</section>
{% endblock %}