base/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('base.views',
    url(r'^$', 'index', name='index'),
    url(r'^howto/$', 'howto', name='howto'),
    url(r'^success/$', 'success', name='success'),
    url(r'^test/$', 'test', name='test'),
    url(r'^get_flatpage_url/$', 'get_flatpage_url', name='get_flatpage_url'),
    url(r'^get_form_url/$', 'get_form_url', name='get_form_url'),
    url(r'^plan/$', 'plan', name='plan'),
    url(r'^probki_value/$', 'get_yandex_probki', name='get_yandex_probki'),
    url(r'^flatpages/(?P<slug>.*)/$', 'flat_page', name='flat_page'),
    url(r'^search/$', 'search', name='search'),

    
    url(r'^check_fp_menuitem_exists/$', 
        'check_fp_menuitem_exists',
        name='check_fp_menuitem_exists'),
)

calendar_expo/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('calendar_expo.views',
    url(r'^$', 'events', name='events'),
    url(r'^api/event_titles/$', 'event_title_list', name='event_title_list'),
    url(r'^api/events/$', 'api_event_list', name='api_event_list'),
    url(r'^(?P<slug>.*)/ics/$', 'event_ics', name='event_ics'),
    url(r'^(?P<slug>.*)/csv/$', 'event_csv', name='event_csv'),
    url(r'^(?P<slug>.*)/$', 'detail', name='detail'),
)

kvc/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import forms_builder.forms.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', name='sitemap_xml'),
    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns('',
    url(r'^$', 'base.views.index', name='index'),
    url(r'^current/', include('base.urls', namespace='base')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^calendar/', include('calendar_expo.urls', namespace='calendar')),
    url(r'^dynamic_forms/', include('dynamic_forms.urls', namespace='dynamic_forms')),
    url(r'^filestorage/', include('filestorage.urls', namespace='filestorage')),
    url(r'^howtopage/', include('howtopage.urls', namespace='howtopage')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^organizers/', include('organizers_app.urls', namespace='organizers')),
    url(r'^press/', include('press_app.urls', namespace='press')),
    url(r'^partners/', include('partners.urls', namespace='partners')),
    url(r'^plans/', include('plans.urls', namespace='plans')),
    url(r'^publications/', include('publications.urls', namespace='publications')),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forms/', include(forms_builder.forms.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    url(r'^$', 'base.views.index', name='i18n_index'),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

urlpatterns += patterns('',
    url(r'^(?P<url>.*)/$', 'base.views.flatpage', name='base.views.flatpage'),
)

urlpatterns += i18n_patterns('',
    url(r'^(?P<url>.*)/$', 'base.views.flatpage', name='i18n_flatpage'),
)

partners/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('partners.views',
    url(r'^$', 'partners', name='partners'),
    #url(r'^(?P<pk>\d+)/$', 'detail', name='detail'),
)

partners/models.py
# coding: utf-8
from django.conf import settings
#from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from easy_thumbnails.files import get_thumbnailer
from filer.fields.image import FilerImageField

from base.defaults import SITE_HELP_TEXT
from base.models import SimpleAbstractPage


class PartnerType(models.Model):
    u''' Тематики новостей '''
    ru_title = models.CharField(_(u'Заголовок (рус.)'), max_length=255)
    en_title = models.CharField(_(u'Заголовок (англ.)'), max_length=255)
    cn_title = models.CharField(_(u'Заголовок (кит.)'), max_length=255)

    def __unicode__(self):
        return self.title()

    def title(self, request=None):
        if request:
            return {
                    'ru': self.ru_title,
                    'en': self.en_title,
                    'zh-cn': self.cn_title,
            }.get(request.LANGUAGE_CODE)
        return self.ru_title

    class Meta:
        verbose_name = _(u'Класс партнера')
        verbose_name_plural = _(u'Классы партнеров')


class Partner(SimpleAbstractPage):
    u''' партнер '''
    site = models.URLField(_(u'сайт'), help_text=SITE_HELP_TEXT)
    en_site = models.URLField(_(u'сайт (англ.)'), help_text=SITE_HELP_TEXT,
                            blank=True)
    cn_site = models.URLField(_(u'сайт (кит.)'), help_text=SITE_HELP_TEXT,
                            blank=True)
    partnertype = models.ForeignKey(PartnerType,
                                    verbose_name=PartnerType._meta.verbose_name)
    flr_image = FilerImageField(verbose_name=_(u'Изображение баннера'),
                                related_name='ru_partners',
                                null=True, blank=True)
    en_image = FilerImageField(verbose_name=_(u'Изображение (англ.)'),
                                null=True,blank=True,
                                related_name='en_partners')
    cn_image = FilerImageField(verbose_name=_(u'Изображение (кит.)'),
                                null=True,blank=True,
                                related_name='cn_partners')
    on_main_page = models.BooleanField(_(u'Показывать на главной'), default=True)
    order = models.IntegerField(_(u'Порядок отображения'), default=0)

    def __unicode__(self):
        return self.title() or u'{0} {1}'.format(self._meta.verbose_name,
                                                self.site) 
    def __init__(self, *args, **kwargs):
        super(Partner, self).__init__(*args, **kwargs)
        field = self._meta.get_field_by_name('ru_content')[0]
        field.blank = True

    def image(self, request=None):
        if request and request.LANGUAGE_CODE:
            return {
                    'ru': self.flr_image,
                    'en': self.en_image,
                    'zh-cn': self.cn_image,
            }.get(request.LANGUAGE_CODE)
        return self.flr_image

    def image_url(self, request=None):
        image = self.image(request) or self.flr_image
        if image:
            opts = dict(size=(160,80))
            thumbnail = get_thumbnailer(image).get_thumbnail(opts)
            return thumbnail.url
        return settings.STATIC_URL+'images/partner3.png'

    def cur_site(self, request=None):
        site = self.site
        if request and request.LANGUAGE_CODE:
            site = {
                    'ru': self.site,
                    'en': self.en_site,
                    'zh-cn': self.cn_site,
            }.get(request.LANGUAGE_CODE)
        return site or self.site
    
    class Meta:
        verbose_name = _(u'партнер')
        verbose_name_plural = _(u'партнеры')
        ordering = 'order',

    #def get_absolute_url(self):
        #return reverse('partners:detail', kwargs=dict(pk=self.pk))

base/forms.py
#coding: utf-8
from django.utils.translation import ugettext_lazy as _

from .fields import LocaleModelSelect2MultipleField, LocaleModelChoiceField


class LocaleFieldModelFormMixin(object):
    def get_locale_field(self, model, request, multiple=True):
        kwargs = dict(  queryset=model.objects.all(),
                        required=False,
                        request=request)
        if multiple:
            return LocaleModelSelect2MultipleField(**kwargs)
        else:
            return LocaleModelChoiceField(**kwargs)

    def get_empty_label(self, request=None):
        return _(u'Любое')

base/views.py
#coding: utf-8
import datetime
import itertools
import json
import requests

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse, Http404
from django.shortcuts import redirect
from django.views.generic import DetailView
from django.views.generic import TemplateView
from django.views.generic import ListView

from calendar_expo.models import Event, BannerItem, MainBigBanner
from dynamic_forms.models import Form
from news.forms import SubscribeEmailForm
from news.models import NewsPage
from partners.models import Partner as PartnerBannerItem

from .models import FlatPage, SliderItem, AbstractPage, EmailTemplate
from .models import SystemTunes, MenuItem
from .utils import send_email


class CTXMixin(object):
    def get_context_data(self, **kwargs):
        ctx = super(CTXMixin, self).get_context_data(**kwargs)
        try:
            ctx['page_title'] = self.model._meta.verbose_name_plural
        except: pass
        ctx['subscribe_form'] = SubscribeEmailForm(self.request)
        return ctx


class IndexPage(CTXMixin, TemplateView):
    u''' Главная страница '''
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        # TODO: need refact
        news = NewsPage.objects.active_pages(self.request)
        if news.count() > 3:
            news =news[:3]
        events = Event.objects.active_pages(self.request
                            ).filter(end_date__gte=datetime.date.today())
        if events.count() > 3:
            events = events[:3]
        sliders = SliderItem.objects.active_pages(self.request
                                    ).filter(is_active=True)
        banners = BannerItem.objects.active(self.request
                                    ).filter(is_active=True,
                                    event__end_date__gte=datetime.date.today())
        partner_banners = PartnerBannerItem.objects.filter(on_main_page=True,
            flr_image__isnull=False)
        if partner_banners.count() > 15:
            partner_banners = partner_banners[:15]
        big_banners = MainBigBanner.objects.active(self.request
                                            ).filter(is_active=True,)
        if big_banners.count() > 2:
            big_banners = big_banners[:2]
        ctx.update({
                    'banners': banners,
                    'big_banners': big_banners,
                    'calendar_events': events,
                    'news': news,
                    'partner_banners': partner_banners,
                    'sliders': sliders,
        })
        return ctx
index = IndexPage.as_view()
success = IndexPage.as_view(template_name='success.html')
test = IndexPage.as_view(template_name='test.html')
plan = IndexPage.as_view(template_name='plan.html')
howto = IndexPage.as_view(template_name='howto.html')

class ListPage(CTXMixin, ListView):
    model = NewsPage
    paginate_by = 10
    template_name = 'basecontent.html'  
news_list = ListPage.as_view()


class DetailPage(CTXMixin, DetailView):
    template_name = 'object_detail.html'
    context_object_name = 'detail_page'

    def get_template_names(self):
        if self.get_object() and self.get_object().template:
            return [self.get_object().template]
        else:
            return super(DetailPage, self).get_template_names()

    def get(self, request, *args, **kwargs):
        if self.get_object() in self.get_queryset().active_pages(request):
            return super(DetailPage, self).get(request, *args, **kwargs)
        else:
            return redirect(reverse('base:index'))
flat_page = DetailPage.as_view(model=FlatPage)


class FlatPageDetail(DetailPage):
    model=FlatPage
    url_kwarg = 'url'

    def get_object(self, queryset=None):    
        if queryset is None:
            queryset = self.get_queryset()
        url = self.kwargs.get(self.url_kwarg, None)
        if not url.startswith('/'): url = '/' + url
        if not url.endswith('/') and settings.APPEND_SLASH: url += '/'
        if url is not None:
            obj = queryset.filter(url_path=url).last()
            if not obj: raise Http404
            return obj
flatpage = FlatPageDetail.as_view()


def check_fp_menuitem_exists(request):
    if request.GET.get('pk'):
        mi = MenuItem.objects.filter(fp=request.GET.get('pk')).last()
        if mi:
            res = dict( exist=True,
                        mi=dict(pk=mi.pk, url=mi.admin_link)
                    )
            return HttpResponse(json.dumps(res),
                                content_type="application/json")
    return HttpResponse(json.dumps(dict(exist=False)), 
                        content_type="application/json")


def get_flatpage_url(request):
    if request.GET.get('pk'):
        fp = FlatPage.objects.filter(pk=request.GET.get('pk')).last()
        if fp:
            return HttpResponse(json.dumps(fp.get_absolute_url()),
                                content_type="application/json")
    return HttpResponse(json.dumps(dict()), 
                        content_type="application/json")

def get_form_url(request):
    if request.GET.get('pk'):
        fp = Form.objects.published(for_user=request.user
                        ).filter(pk=request.GET.get('pk')
                        ).last()
        if fp:
            return HttpResponse(json.dumps(fp.get_absolute_url()),
                                content_type="application/json")
    return HttpResponse(json.dumps(dict()), 
                        content_type="application/json")

def get_flat_list(gen):
    return list(itertools.chain(*gen))

def get_subclass_queryset(model, filters):
    for sub_model in model.__subclasses__():
        if not sub_model.__subclasses__():
            yield sub_model.objects.filter(filters)
        #if sub_model.__subclasses__():
            #yield get_flat_list(get_subclass_queryset(sub_model, filters))
        #else:
            #yield sub_model.objects.filter(filters)

class Search(TemplateView):
    u''' поиск по сайту '''
    template_name = 'search.html'

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        ctx['search_results'] = self.get_pages()
        return ctx

    def get_pages(self):
        if self.request.GET.get('keyword'):
            filters = self.get_filters()
            res = get_subclass_queryset(AbstractPage, filters)
            return get_flat_list(res)

    def get_filters(self):
        dct = self.request.GET.get('keyword', '').split(' ')
        q = None
        for s in dct:
            prefix = {
                        'ru': 'ru',
                        'en': 'en',
                        'zh-cn': 'cn',
                }.get(self.request.LANGUAGE_CODE)
            fields = ['{0}_{1}'.format(prefix, f) for f in ('title', 'content', 'status')]
            expr1 = Q(**{
                            '{0}__{1}'.format(fields[0], 'isnull'): False,
                            fields[2]: 2,
            })
            expr2 = Q(**{'{0}__{1}'.format(fields[0], 'icontains'): s})
            expr3 = Q(**{'{0}__{1}'.format(fields[1], 'icontains'): s})
            expr = (expr1 & (expr2 | expr3))
            if q:
                q|= expr
            else:
                q = expr
        return q
search = Search.as_view()


def get_yandex_probki(request):
    url = 'http://jgo.maps.yandex.net/trf/stat.js?='
    r = requests.get(url)
    if r.status_code == 200:
        res = r.text[r.text.find('[')+1:-4].split('},{')[0][1:]
        res = res[res.find('level:"'):].split('"')[1]
        return HttpResponse(res)
    return HttpResponse(json.dumps(dict()))


class SendEmailMixin(object):
    def send_email(self, obj, email_tpl_type, to_attr):
        email_tpl = EmailTemplate.objects.filter(tpl_type=email_tpl_type).last()
        st = SystemTunes.objects.get_current()
        if email_tpl:
            bctx = dict(obj=obj,)
            send_email( 
                        subject=email_tpl.subject,
                        to = getattr(st,to_attr),
                        body_tpl = email_tpl.text,
                        body_context = bctx,
                        from_email = st.from_email
                    )

partners/views.py
#coding: utf-8
from django.db.models import Q
from django.views.generic.list import ListView

from base.views import DetailPage, CTXMixin

from .models import Partner, PartnerType


class Partners(CTXMixin, ListView):
    u''' страница новостей'''
    template_name = 'partners.html'
    model = Partner
    paginate_by = 10

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        subjects = PartnerType.objects.all()
        ctx['subjects'] = subjects
        return ctx

    def get_queryset(self):
        qs = super(self.__class__, self).get_queryset(
                                       )#.active_pages(self.request)
        #TODO: refact this
        q = Q()
        if self.request.GET:
            body = self.request.GET
            if body.getlist('partnertype__pk'):
                q&= Q(partnertype__pk__in=body.getlist('partnertype__pk'))
        return qs.filter(q)
partners = Partners.as_view()

detail = DetailPage.as_view(model=Partner)

base/templates/partial/announcements.html
{% load block_render_tags i18n pytils_dt %}
<div class="announcements">
    <h3>{% trans 'Ближайшие события' %}</h3>
    {% if calendar_events %}
        <ul class="announcementslist">
            {% for event in calendar_events %}
                <li class="announcement">
                    <a href="{{event.get_absolute_url}}">
                        {% if LANGUAGE_CODE == 'ru' %}
                        <time>{{event.start_date|ru_strftime:"%d %B"}} – {{event.end_date|ru_strftime:"%d %B"}}</time>
                        {% else %}
                        <time>{{event.start_date|date:"d F"}} – {{event.end_date|date:"d F"}}</time>
                        {% endif %}
                        <br/>
                        {% render_locale_title request event %}
                    </a>
                </li>
            {% endfor%}
        </ul>
    {% endif %}
    <a href="{% url 'calendar:events' %}" class="allannouncements"><i class="topsubmenuicon eventscalendaricon"></i>{% trans 'Смотреть все события в календаре' %}</a>
</div>

base/templates/partial/breadcrumbs.html
{% load block_render_tags i18n %}
<div class="breadcrumbs">
    <ul>
        <li><a href="{% url 'index' %}">{% trans 'Главная' %}</a> / </li>
        {% if parentmenu == current_menuitem %}
        <li>
            {% if parent_menu.is_clickable %}<a href="{{parent_menu.url}}">{% endif %}
            {% render_locale_title request parent_menu %}
            {% if parent_menu.is_clickable %}</a>{% endif %} / 
        </li>
        {% endif %}
        <li>{% render_locale_title request current_menuitem %}</li>
    </ul>
</div>

base/templates/partial/empty.html
{% load i18n %}
<p>{% trans 'Нет записей' %}</p>

base/templates/partial/footer.html
{% load i18n %}
<footer>
    <div class="container">
        <div class="copyright">
            <a href="http://indev-group.ru/">{% trans 'Разработано в ИнДев Групп' %}</a>
        </div>
        <div class="footercontacts">
        {% if footer_block_content.info %}
            {{footer_block_content.info.phone}} <a href="mailto:{{footer_block_content.info.email}}">{{footer_block_content.info.email}}</a>
        {% endif %}
        </div>
        <div class="footersocial">
            <p>{% trans 'Экспофорум в соцсетях' %}:</p>
            <ul class="sociallinks">
                {% for item in footer_block_content.net.all %}
                    <li><a href="{{item.site}}" class="socialicon {{item.net_type}}"  target="_blank">{{item.net_type}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</footer>

base/templates/partial/head.html
{% load staticfiles %}
<head>
    {% block seo %}
    <title>ExpoForum</title>
    {% endblock %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "css/fancyfields.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "css/jquery.jscrollpane.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "css/jquery-ui-1.10.4.custom.min.css" %}" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="{% static "js/jquery-1.11.0.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.jcarousel.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/fancyfields-1.2.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.mousewheel.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.jscrollpane.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery-ui-1.10.4.custom.min.js" %}"></script>
    {% if LANGUAGE_CODE == 'ru' %}
    <script type="text/javascript" src="{% static "js/jquery.ui.datepicker-ru.js" %}"></script>
    {% endif %}
    {% if LANGUAGE_CODE == 'zh-cn' %}
    <script type="text/javascript" src="{% static "js/jquery.ui.datepicker-zh-cn.js" %}"></script>
    {% endif %}
    <script type="text/javascript" src="{% static "js/main.js" %}"></script>
    <!--[if lt IE 9]>
        <script src="{% static "js/html5shiv.js" %}"></script>
    <![endif]-->
    <!--[if IE]>
        <link href="{% static "images/design/favicon.ico" %}" rel="icon" type="image/x-icon"/>
    <![endif]-->
    <link href="{% static "images/design/favicon.png" %}" rel="icon" type="image/png"/>
</head>

base/templates/partial/header.html
{% load i18n %}
{% load staticfiles %}
{% load block_render_tags %}
<header>
    <div class="container">
        <div class="headlogo">
            <a href="/"><img src="{% static "images/design/logo.png" %}" alt="ExpoForum"></a>
        </div>
        <div class="headcontacts">
        {% if header_block_content.info %}
            {{header_block_content.info.phone}} <a href="mailto:{{header_block_content.info.email}}">{{header_block_content.info.email}}</a>
        {% endif %}
        </div>
        <div class="rightsection">
            <div class="languageselect">
                <form action="{% url 'set_language' %}" method="post" id="languageselect">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{request.get_full_path|strip_lang}}" />
                    <ul>
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                        <li{% if language.code == LANGUAGE_CODE %} class="active"{% endif %}>
                            <a href="#{{ language.code }}" class="languageicon {{ language.code }}">{{ language.name_local }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    <input name="language" type="hidden" value="{{ language.code }}">
                </form>
                {% comment %}
                <script type="text/javascript">
                    $('form#languageselect').on("submit", function () {
                        var next = $(this).find("input[name=next]");
                        var lang = $(this).find("input[name=language]").val();
                        var re = /^(\/)(en|ru)(\/)*/;
                        if (next.val().match(re)) {
                            next.val(next.val().replace(re, "/"+lang+"/"));
                        }
                        else {
                            next.val("/"+lang+next.val());
                        };
                    });
                </script>
                {% endcomment %}
            </div>
            <div class="headersearch">
                <form class="" action="{% url 'base:search' %}" method="get">
                    <input type="search" name="keyword" value="" placeholder="{% trans 'Поиск по сайту' %}">
                    <button type="submit" class="headersearchbtn">{% trans 'Найти' %}</button>
                </form>
            </div>
            <div class="headmenu">
                <ul>                
                {% for item in header_block_content.menu.all %}
                    <li><a href="{{item.menuitem.url}}" >{% render_locale_title request item.menuitem %}</a></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</header>

base/templates/partial/mainnav.html
{% load block_render_tags %}
<nav class="mainnav">
    <ul class="mainnavlist">
    {% for item in main_navigation_block.menu.all %}
        <li>
            {% if item.menuitem.is_clickable %}
                <a href="{{item.menuitem.url}}" class="mainnavlink">
                    {% render_locale_title request item.menuitem %}
                </a>
            {% else %}
                <div class="mainnavlink">
                    {% render_locale_title request item.menuitem %}
                </div>
            {% endif %}
            {% if item.menuitem.children.all %}
            <ul class="mainnavsublist">
                {% for child in item.menuitem.children.all %}
                <li><a href="{{child.url}}">{% render_locale_title request child %}</a></li>
                {% endfor %}
            </ul>
            {% endif %}
        </li>
    {% endfor %}

    </ul>
</nav>

base/templates/partial/middleblock.html
{% load block_render_tags %}
{% load staticfiles %}
<div class="middlecontentblock">
    <div class="promoblockspart">
        {% for banner in big_banners %}
        <div class="promoblock">
            <a href="{% render_locale_url request banner 'event_url' %}" target="_blank">
                <img src="{% render_locale_url request banner 'image_url' %}" alt="{{banner}}">
            </a>
        </div>
        {% endfor %}
    </div>

    <div class="newsbar">
        {% include 'partial/newsbar.html'%}
    </div>
    {% include 'partial/partners.html' %}
</div>

base/templates/partial/newsbar.html
{% load block_render_tags i18n %}
<h3>{% trans 'Новости' %}</h3>
<ul class="newsbarlist">
    {% for page in list %}
        <li class="newsbaritem">
            <p><time>{{page.created}}</time></p>
            <p><a href="{{page.get_absolute_url}}" >{% render_locale_title request page %}</a></p>
        </li>
    {% endfor %}
</ul>
<div class="subscribeblock">
    <a href="{% url link %}" class="allnewslink newsicon">{% trans 'Читать все новости' %}</a>
</div>

base/templates/partial/paginator.html
{% load i18n %}
<div class="paginationblock">
    <ul class="pageslist">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">{% trans 'Предыдущая' %}</a></li>
        {% endif %}
        {% if is_paginated %}
        {% for n in paginator.page_range %}
        {% if forloop.counter0 < 5 or forloop.last  or forloop.counter == page_obj.number %}
        <li><a href="?page={{n}}" {% ifequal n page_obj.number %}class="currentPage"{%endifequal%}>{{n}}</a></li>
        {% endif %}
        {% endfor %}
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">{% trans 'Следующая' %}</a></li>
        {% endif %}
    </ul>
</div>

base/templates/partial/partners.html
{% load block_render_tags i18n %}
<div class="partnersblock">
   <a href="{% url 'partners:partners' %}"><h3>{% trans 'Партнеры' %}</h3></a>
    <div class="partnersview" id="partners">
        <ul class="partnerslist">
        {% for item in partner_banners %}
            {% if not forloop.counter|divisibleby:"2" %}
            <li class="partnerscell">
            {%endif%}
                <a href="{% render_locale_url request item 'cur_site' %}" class="partnerbox" target="_blank">
                    <div class="partnerboxlogo" style="background-image:url({% render_locale_url request item 'image_url' %})">
                        <img src="{% render_locale_url request item 'image_url' %}" alt="{% render_locale_title request item %}">
                    </div>
                </a>
            {% if forloop.counter|divisibleby:"2" %}
            </li>
            {%endif%}
        {% endfor %}
        </ul>
    </div>
    <a href="#" class="partnersnav prev" id="prevslide">&lt;</a>
    <a href="#" class="partnersnav next" id="nextslide">&gt;</a>
</div>

base/templates/partial/sidebar.html
<div class="sidebar">
    {% include 'partial/topsubmenu.html' %}
    {% include 'partial/sidebar/bluebanner.html' with type=1 %}
    {% include 'partial/sidebar/banner.html' %}
</div>

base/templates/partial/topblock.html
{% load i18n %}
<div class="topcontentblock">
    {% include 'partial/topblock/slider.html' %}
    {% include 'partial/mainnav.html' %}
    <div class="infobannersblock">
        {% include 'partial/announcements.html' %}
        {% include 'partial/topblock/banners.html' %}
    </div>
</div>