kvc/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import forms_builder.forms.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', name='sitemap_xml'),
    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns('',
    url(r'^$', 'base.views.index', name='index'),
    url(r'^current/', include('base.urls', namespace='base')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^calendar/', include('calendar_expo.urls', namespace='calendar')),
    url(r'^dynamic_forms/', include('dynamic_forms.urls', namespace='dynamic_forms')),
    url(r'^filestorage/', include('filestorage.urls', namespace='filestorage')),
    url(r'^howtopage/', include('howtopage.urls', namespace='howtopage')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^organizers/', include('organizers_app.urls', namespace='organizers')),
    url(r'^press/', include('press_app.urls', namespace='press')),
    url(r'^partners/', include('partners.urls', namespace='partners')),
    url(r'^plans/', include('plans.urls', namespace='plans')),
    url(r'^publications/', include('publications.urls', namespace='publications')),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forms/', include(forms_builder.forms.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    url(r'^$', 'base.views.index', name='i18n_index'),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

urlpatterns += patterns('',
    url(r'^(?P<url>.*)/$', 'base.views.flatpage', name='base.views.flatpage'),
)

urlpatterns += i18n_patterns('',
    url(r'^(?P<url>.*)/$', 'base.views.flatpage', name='i18n_flatpage'),
)

organizers_app/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('organizers_app.views',
    url(r'^halls/$', 'halls', name='halls'),
    url(r'^hall/(?P<slug>.*)/$', 'hall', name='hall'),
    url(r'^ordering/hall/$', 'hall_order', name='hall_order'),
    url(r'^ordering/hall/(?P<hall_slug>.*)/$', 'hall_order', name='hall_order'),
)

organizers_app/models.py
# coding: utf-8
import datetime

from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from base.models import AbstractPage, TitlePage

#from .choices import CAPACITY


class House(AbstractPage):
    class Meta:
        verbose_name = _(u'Здание')
        verbose_name_plural = _(u'Здания')


class SeatingType(TitlePage):
    class Meta:
        verbose_name=_(u'Тип рассадки')
        verbose_name_plural=_(u'Типы рассадки')

class Hall(AbstractPage):
    house = models.ForeignKey(House, verbose_name=House._meta.verbose_name,
                            null=True, blank=True)
    seating_type = models.ForeignKey(SeatingType, null=True, blank=True,
                                    verbose_name=_(u'Тип рассадки'))
    capacity = models.PositiveIntegerField(_(u'Вместимость зала, чел'),
                                            default=0)
    images = models.ManyToManyField('filestorage.Mediafile', null=True)
    
    class Meta:
        verbose_name = _(u'Зал')
        verbose_name_plural = _(u'Залы')

    def get_absolute_url(self):
        return reverse('organizers:hall', kwargs=dict(slug=self.slug))


class HallOrder(models.Model):
    title = models.CharField(_(u'Название мероприятия'), max_length=255)
    capacity = models.CharField(_(u'Количество участников'), max_length=255,
                                blank=True, null=True)
                                            #choices=CAPACITY)
    start_date = models.DateField(_(u'начало'),default=datetime.date.today())
    end_date = models.DateField(_(u'окончание'),default=datetime.date.today())
    hall = models.ForeignKey(Hall, verbose_name=Hall._meta.verbose_name,
                            null=True, blank=True)
    extra_need = models.BooleanField(
        _(u'Необходимы дополнительные услуги'), default=False, 
        help_text=_(u'Например: кейтеринг, аренда оборудования, перевод')
    )
    contact_name = models.CharField(_(u'Имя'), max_length=255)
    contact_phone = models.CharField(_(u'Телефон'), max_length=255)
    contact_email = models.EmailField(_(u'Email'))
    desc = models.TextField(_(u'Дополнительное описание мероприятия'),
                                max_length=2048, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'{0} {1}'.format(self.title, self.created)

    class Meta:
        ordering = '-created', 'start_date', 'end_date', 'hall'
        verbose_name = verbose_name_plural =_(u'Бронирование зала')

    @property
    def admin_link(self):
        if self.pk:
            return reverse('admin:organizers_app_hallorder_change',
                            args=(self.pk,),)
    @property
    def absolute_admin_link(self):
        return 'http://'+Site.objects.get_current().domain+self.admin_link

organizers_app/forms.py
#coding: utf-8
from django import forms

from .models import HallOrder


class HallOrderForm(forms.ModelForm):
    class Meta:
        model = HallOrder

    def __init__(self, *args, **kwargs):
        super(HallOrderForm, self).__init__(*args, **kwargs)
        self.fields['hall'].empty_label=None
        for k,v in self.fields.items():
            if self.fields[k].required:
                v.widget.attrs['required']='required'
            if k == 'capacity':
                v.initial = None

organizers_app/views.py
#coding: utf-8
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.views.generic import CreateView, ListView
from django.shortcuts import get_object_or_404

from base.models import ExpoType
from base.views import CTXMixin, DetailPage, SendEmailMixin

from .forms import HallOrderForm
from .models import Hall, HallOrder#, SeatingType

class HallsPage(CTXMixin, ListView):
    model = Hall
    paginate_by = 10
    template_name = 'halls.html'

    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        ctx['titles'] = self.model.objects.active_pages(self.request)
        ctx['seating_types'] = ExpoType.objects.all()
        ctx['capacity'] = Hall.objects.values_list('capacity', flat=True)
        return ctx

    def get_queryset(self):
        qs = super(self.__class__, self).get_queryset(
                                       ).active_pages(self.request)
        #TODO: refact this
        q = Q()
        if self.request.GET:
            body = self.request.GET
            if body.getlist('seaing_type__pk'):
                q&= Q(seaing_type__pk__in=body.getlist('seaing_type__pk'))
            if body.get('capacity'):
                q&= Q(capacity__in=body.getlist('capacity'))
        return qs.filter(q)
halls = HallsPage.as_view()
hall = DetailPage.as_view(model=Hall)

class HallOrdering(CTXMixin, SendEmailMixin, CreateView):
    model = HallOrder
    template_name = 'hallorder_form.html'
    form_class = HallOrderForm

    def get_initial(self):
        initial=super(HallOrdering, self).get_initial()
        if self.request.GET.get('room'):
            initial['hall'] = get_object_or_404(Hall, 
                                            pk=self.request.GET.get('room')
                            )
        return initial

    def get_success_url(self):
        obj = self.object
        obj.page_title = u'Онлайн-заявка на организацию мероприятия'
        self.send_email(obj, email_tpl_type=2,to_attr='hall_to')
        return reverse('base:success')
hall_order = HallOrdering.as_view()

organizers_app/templates/hallorder_form.html
{% extends 'basecontent.html' %}

{% load block_render_tags i18n widget_tweaks %}

{% block middle %}
<div class="middlecontentblock">
    <div class="sidebar">
        {% include 'partial/topsubmenu.html' %}
        {% include 'partial/sidebar/bluebanner.html' with type=1 %}
        {% include 'partial/sidebar/banner.html' %}
    </div>
    <div class="mainblock">
        <div class="textblock">
            {#<p><a href="{% url 'organizers:halls' %}">← {% trans 'Вернуться к списку залов' %}</a></p>#}
            <h2>{% trans 'Онлайн-заявка на организацию мероприятия' %}</h2>
            <form class="reserverequest" method="post" action="">
                {% csrf_token %}
                <label>{{form.title.label}}</label>{{form.title.errors}}{{form.title}}
                <label>{{form.capacity.label}}</label>{{form.capacity.errors}}
                {% render_field form.capacity class+="niceselect" type="number" min="1" max="999999999999"%}
                <label>{% trans 'Дата проведения' %}</label>
                <div class="eventdate">
                    <label>{% trans 'С' %}</label>{{form.start_date.errors}}
                    {% render_field form.start_date class+="dateui white" autocomplete="off" %}
                </div>
                <div class="eventdate">
                    <label>{% trans 'По' %}</label>{{form.end_date.errors}}
                    {% render_field form.end_date class+="dateui white" autocomplete="off" %}
                </div>
                <div style="display:none;">{% render_field form.hall class="" %}</div>
                {{form.extra_need|add_class:"nicecheck"}}<label>{{form.extra_need.label}} {{form.extra_need.help_text}}</label>{{form.extra_need.errors}}
                <p class="advancennote">{% trans 'С полным списком дополнительных услуг можно ознакомиться в разделе' %}&nbsp;<a href="/current/flatpages/service/">«{% trans 'Услуги организаторам' %}»</a>.</p>
                <label>{% trans 'Ваше' %} {{form.contact_name.label|lower}}</label>{{form.contact_name.errors}}{{form.contact_name}}
                <label>{{form.contact_phone.label}}</label>{{form.contact_phone.errors}}{{form.contact_phone}}
                <label>{{form.contact_email.label}}</label>{{form.contact_email.errors}}{{form.contact_email}}
                <label>{{form.desc.label}}</label>{{form.desc.errors}}{{form.desc}}
                <button type="submit" class="bluebtn">{% trans 'Отправить заявку' %}</button>
            </form>
            <p>{% trans 'Наши менеджеры свяжутся с вами для уточнения деталей' %}</p>
        </div>
        <div class="clear"><br/></div>
    </div>
</div>
{% endblock %}

organizers_app/templates/halls.html
{% extends 'basecontent.html' %}

{% load block_render_tags i18n %}

{% block middle %}
<div class="middlecontentblock">
    <div class="sidebar">
        {% include 'partial/topsubmenu.html' %}
        {% include 'partial/sidebar/bluebanner.html' with type=1 %}
        {% include 'partial/sidebar/banner.html' %}
    </div>
    <div class="mainblock">
        <div class="textblock greentopblock">
            {# include 'partial/breadcrumbs.html' #}  
            <h2>{% trans 'Подбор зала' %}</h2>
            {% include 'partial/filters.html' %}
        </div>
        <div class="textblock">
            <ul class="roomslist">
                {% for room in object_list %}
                <li class="roomitem">
                    <h3>{% render_locale_title request room %}</h3>
                    <p class="roomsubtype">{% render_locale_title request room.house %}</p>
                    {% render_locale_content request room %}
                    {#<p><a href="#">На интерактивном плане →</a></p>#}
                    <div class="roomgallery">
                        <ul class="roomminipreviewlist">
                            {% for img in room.images.all %}
                            <li><a href="#"><img src="{{img.image.url}}" alt=""></a></li>
                            {%endfor%}
                        </ul>
                        <form action="" method="post" class="roomfastreserv">
                            <a class="bluebtn topmargin" href="{% url 'organizers:hall_order' %}?room={{room.pk}}">{% trans 'Заборнировать зал' %}</a>
                        </form>
                    </div>
                </li>
                {% empty %}
                <li>
                    {% include 'partial/empty.html' %}
                </li>
                {% endfor %}
            </ul>
            {% include 'partial/paginator.html' %}
        </div>
    </div>
</div>
{% endblock %}