kvc/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import forms_builder.forms.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', name='sitemap_xml'),
    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns('',
    url(r'^$', 'base.views.index', name='index'),
    url(r'^current/', include('base.urls', namespace='base')),
    url(r'^company/', include('company.urls', namespace='company')),
    url(r'^calendar/', include('calendar_expo.urls', namespace='calendar')),
    url(r'^dynamic_forms/', include('dynamic_forms.urls', namespace='dynamic_forms')),
    url(r'^filestorage/', include('filestorage.urls', namespace='filestorage')),
    url(r'^howtopage/', include('howtopage.urls', namespace='howtopage')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^organizers/', include('organizers_app.urls', namespace='organizers')),
    url(r'^press/', include('press_app.urls', namespace='press')),
    url(r'^partners/', include('partners.urls', namespace='partners')),
    url(r'^plans/', include('plans.urls', namespace='plans')),
    url(r'^publications/', include('publications.urls', namespace='publications')),
)

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forms/', include(forms_builder.forms.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    url(r'^$', 'base.views.index', name='i18n_index'),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

urlpatterns += patterns('',
    url(r'^(?P<url>.*)/$', 'base.views.flatpage', name='base.views.flatpage'),
)

urlpatterns += i18n_patterns('',
    url(r'^(?P<url>.*)/$', 'base.views.flatpage', name='i18n_flatpage'),
)

news/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('news.views',
    url(r'^$', 'news_list', name='news_list'),
    url(r'^api/list/$', 'api_news_list', name='api_news_list'),
    url(r'^api/subscribe/$', 'subscribe', name='subscribe'),
    url(r'^(?P<slug>.*)/$', 'detail', name='detail'),
)

news/models.py
# coding: utf-8
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from base.models import AbstractPage


class NewsSubjects(MPTTModel):
    u''' Тематики новостей '''
    ru_title = models.CharField(_(u'Заголовок (рус.)'), max_length=255)
    en_title = models.CharField(_(u'Заголовок (англ.)'), max_length=255)
    cn_title = models.CharField(_(u'Заголовок (кит.)'), max_length=255)
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='children', verbose_name=_(u'родитель'))
    order = models.PositiveIntegerField(_(u'Сортировка'))

    class MPTTMeta:
        order_insertion_by = ('order',)

    def save(self, *args, **kwargs):
        super(self.__class__, self).save(*args, **kwargs)
        self.__class__.objects.rebuild()

    def __unicode__(self):
        return self.title()

    def title(self, request=None):
        if request:
            return {
                    'ru': self.ru_title,
                    'en': self.en_title,
                    'zh-cn': self.cn_title,
            }.get(request.LANGUAGE_CODE)
        return self.ru_title

    def get_pages(self,request=None):
        if not self.parent:
            qs = self.newspage_set.model.objects.filter(subjects__parent=self)
            if request:
                qs = qs.active_pages(request)
            return qs

    class Meta:
        verbose_name = _(u'Тематика новостей')
        verbose_name_plural = _(u'Тематики новостей')


class NewsPage(AbstractPage):
    u''' Новости портала '''
    subjects = models.ForeignKey(NewsSubjects, verbose_name=_(u'Тематика'))
    event = models.ForeignKey('calendar_expo.Event',
                            verbose_name=_(u'Выставка'), null=True, blank=True)

    class Meta:
        ordering = ('-created',)
        verbose_name= _(u'Новости портала')
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('news:detail', kwargs=dict(slug=self.slug))


class SubscribeEmail(models.Model):
    subjects = models.ForeignKey(NewsSubjects, verbose_name=_(u'Тематика'),
                                null=True, blank=True)
    event = models.ForeignKey('calendar_expo.Event', verbose_name=_(u'Выставка'),
                                null=True, blank=True)
    email = models.EmailField(_('email'))

    __unicode__ = lambda self: self.email

    class Meta:
        verbose_name=_(u'Подписка новостей')
        verbose_name_plural = verbose_name

news/forms.py
#coding: utf-8
from django import forms

from base.forms import LocaleFieldModelFormMixin
from calendar_expo.models import Event

from .models import SubscribeEmail, NewsSubjects


class SubscribeEmailForm(LocaleFieldModelFormMixin, forms.ModelForm):
    class Meta:
        model = SubscribeEmail

    def __init__(self, request=None, *args, **kwargs):
        super(SubscribeEmailForm, self).__init__(*args, **kwargs)
        self.fields['event'] = self.get_locale_field(Event,request, 
                                                    multiple=False)
        self.fields['subjects'] = self.get_locale_field(NewsSubjects,request, 
                                                        multiple=False)

news/views.py
#coding: utf-8
from django.db.models import Q
from django.views.generic import DetailView
from django.views.generic.list import ListView

from rest_framework import generics

from base.views import CTXMixin

from .models import NewsPage, NewsSubjects, SubscribeEmail
from .serializers import NewsPageSerializer

class NewsMixin(CTXMixin):
    u''' страница новостей'''
    template_name = 'news_list.html'
    model = NewsPage
    paginate_by = 3

    def get_queryset(self):
        qs = super(NewsMixin, self).get_queryset(
                                       ).active_pages(self.request)
        #TODO: refact this
        q = Q()
        body = self.request.GET or getattr(self.request, 'QUERY_PARAMS', None)
        if body:
            if body.getlist('pk'):
                q&= Q(pk__in=body.getlist('pk'))
            if body.getlist('subjects__pk'):
                q&= (   Q(subjects__pk__in=body.getlist('subjects__pk')) |
                        (   Q(subjects__parent__isnull=False) &
                            Q(subjects__parent__pk__in=body.getlist('subjects__pk'))
                        )
                    )
        return qs.filter(q)


class APINewsList(NewsMixin, generics.ListAPIView):
    u''' '''
    serializer_class = NewsPageSerializer
api_news_list = APINewsList.as_view()

class NewsList(NewsMixin, ListView):
    u''' страница новостей'''
    def get_context_data(self, **kwargs):
        ctx = super(self.__class__, self).get_context_data(**kwargs)
        ctx['titles'] = self.model.objects.active_pages(self.request)
        subjects = NewsSubjects.objects.all()
        ctx['subjects'] = subjects.filter(parent__isnull=True)
        return ctx
news_list = NewsList.as_view()

class NewsDetail(CTXMixin, DetailView):
    model=NewsPage
    template_name='news_detail.html'
    context_object_name = 'detail_page'
detail = NewsDetail.as_view()


class SubscribeForm(generics.CreateAPIView):
    model = SubscribeEmail
subscribe = SubscribeForm.as_view()

news/templates/news_detail.html
{% extends 'basecontent.html' %}

{% load block_render_tags i18n %}

{% block middle %}
<div class="middlecontentblock">
    {% include 'partial/sidebar.html' %}
    <div class="mainblock">
        <div class="textblock newstext">
            {# include 'partial/breadcrumbs.html' #}
            <h2>{% render_locale_title request detail_page %}</h2>
            {% if detail_page.show_date %}<time>{{detail_page.created}}</time>{% endif %}
            {% if detail_page.content %}
            {% render_locale_content request detail_page %}
            {% endif %}
            {% if form %}
                {% render_built_dynform form %}
            {% endif %}
            <p><a href="{% url 'news:news_list' %}" class="rightlink">{% trans 'Все новости' %}</a></p>
        </div>
    </div>
</div>
{% endblock %}

news/templates/news_list.html
{% extends 'basecontent.html' %}

{% load block_render_tags i18n %}

{% block middle %}
<div class="middlecontentblock">
    {% include 'partial/sidebar.html' %}
    <div class="mainblock">
        <div class="textblock news">
            <h2><a href="{% url 'news:news_list' %}" style="color:#fff;text-decoration:none;">{% trans 'Новости' %}</a></h2>
            {% include 'partial/news_filter.html' %}
        </div>
        <div class="textblock">
            <ul class="newslist">
                {% for newspage in newspage_list %}
                <li class="newsitem">
                    <div class="newstimeblock">{% if newspage.show_date %}<time>{{newspage.created}}</time>{% endif %}</div>                    
                    <div class="newsitemtext">
                        <h3><a href="{{newspage.get_absolute_url}}" target="_blank">{% render_locale_title request newspage %}</a></h3>
                        {% render_locale_content request newspage %}
                    </div>
                </li>
                {% empty %}
                    <li class='newsitem'>{% trans 'Нет новостей' %}</li>
                {% endfor %}
            </ul>
            {% include 'partial/paginator.html' %}
        </div>
    </div>
</div>
{% endblock %}

{% block extrascripts %}
{{block.super}}
<script type="text/javascript">
$(document).ready(function() {
    function base_logic(event, th) {
        event.stopPropagation();
        var indextab = th.parent().index();
        th.parent().siblings().removeClass('active');
        th.parent().addClass('active');
        th.parent().parent().parent().find('.tabsblockpage:eq('+indextab+')').addClass('active').siblings().removeClass('active');
    };
    $('.tabscontrol > li > a').on("click", function(event){
        base_logic(event, $(this));
        event.preventDefault();
        var link = $(this);
        if (link.attr('href')) {
            var params = link.attr('href').split('?')[1];
            get_news_data(params);
        }
    });
    $('ul.pageslist').on("click", 'a', function(event){
        //event.stopPropagation();
        event.preventDefault();
        var link = $(this);
        if (link.attr('href')) {
            var params = link.attr('href').split('?')[1];
            get_news_data(params);
        }
    });
    $('.newsfilter input[type=checkbox]').fancyfields({
        onCheckboxChange: function (input, isChecked) {
            input.closest('form').submit();
        }
    });
    $('form.newsfilter').on("submit", function(event){
        base_logic(event, $(this));
        event.preventDefault();
        var params = $(this).serialize();
        if (params) {
            get_news_data(params);
        }
    });
    function get_news_data(params) {
        var url = '{% url 'news:api_news_list' %}'
        if (params) {
            url = url + '?' + params;
        }
        $.ajax({
            url: url,
            success: function( data ) {
                set_news(data);
            }
        });
    };

    function set_news(data) {
        set_pagination(data);

        var newslist = $('ul.newslist')
        newslist.empty();
        if (data.results.length > 0) {
            $.each(data.results, function (index, element) {
                var created = '';
                if (element.show_date) {
                    created = element.created;
                }
                newslist.append('<li class=\"newsitem\"><div class=\"newstimeblock\"><time>'+created+'</time></div><div class=\"newsitemtext\"><h3><a href=\"'+element.url+'\" target=\"_blank\">'+element.title+'</a></h3>'+element.content+'</div></li>')
            });
            $("a.fancybox").attr('rel', 'gallery').fancybox();
        }
        else {
            newslist.append('<li class=\"newsitem\">'+'{% trans 'Нет новостей' %}'+'</li>')
        };
    };

    function set_pagination(data) {
        var paginator = $('ul.pageslist');
        paginator.empty();
        if (data.pages.length > 1) {
            if (data.previous) {
                var href = data.previous.split('?')[1];
                paginator.append('<li><a href=\"?'+href+'\">'+'{% trans 'Предыдущая' %}'+'</a></li>');
            };
            if (data.pages && data.viewable_pages) {
                set_paginator_pages(data, paginator);
            };
            if (data.next) {
                var href = data.next.split('?')[1];
                paginator.append('<li><a href=\"?'+href+'\">'+'{% trans 'Следующая' %}'+'</a></li>');
            };
        };
        $('.pageslist a').click(function(e){
            $('.middlecontentblock').ScrollTo({offsetTop: 100});
        });
    }
});
</script>
{% endblock %}